### ISSUE TITLE
Unable to fetch link after upload

### ISSUE THREAD

**Issue by scottyeung** [nina-market/nina#86]
Unable to fetch link once the transaction is approved and assets are uploaded 

<img width="1432" alt="Screenshot 2021-11-25 at 5 52 53 PM" src="https://user-images.githubusercontent.com/23536187/143434946-308b0de7-add7-4497-ab05-1b18d0127c8f.png">

**Comment by facing-n** [comment]
We definitely have an unsafe unwrap here - fixed in #87 

Are you sure that you didn't cancel the request here?

looks like a possibility from phantom docs: https://docs.phantom.app/integrating/errors

<img width="781" alt="Screen Shot 2021-11-25 at 10 02 17 AM" src="https://user-images.githubusercontent.com/2960410/143464529-eeed9572-903c-4575-b429-5769ac7d94f2.png">

**Comment by scottyeung** [comment]
Think the validation was missed out in `ReleaseContext`. Once I rejected the request, the context was reseted with something else in such edge case? Or could be Formik sends out an undefined payload after failure? 

<img width="1056" alt="Screenshot 2021-11-26 at 3 15 14 AM" src="https://user-images.githubusercontent.com/23536187/143492009-22e0ea7c-f7cf-4eac-bac2-1f15c09a16fc.png">

**Comment by facing-n** [comment]
Ah - you are correct it looks like something is getting stale in the case of a cancelled or failed attempt - need to make sure state is reset in that case @ejf89
